# Python review 

Goals:
- recall basic Python vocabulary 
- practice markdown 

## Libraries and packages 
**library** a collection of code we can use to perform specfic tasks in our programs. 

**Numpy**: 
- core library for numerical computing in Python 
- many other libraries use NumPy arrays as building blocks 
- computations on NumPy are optimized for speed and memory usage

Let's import NumPy with **standard abbreviation** 


In [2]:
import numpy as np

## Variables 

**variable**: a name we assign to a particular object in Python 

Example: 

In [4]:
# Assign a small array to a variables a 
a = np.array([[1,2,2],[3,5,8]])


In [6]:
# Run cell with a variable name to show value
a

array([[1, 2, 2],
       [3, 5, 8]])

In [7]:
# Use 'print' function to print the value 
print(a)

[[1 2 2]
 [3 5 8]]


## Objects 

**object** (informally speaking) is a bundle of *properties* and *actions* about something specfic. 

Example: 
Object: data frame 
Properties: number of tows, names of the columns, date created 
Actions: Selecting a specific row, adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables. 

In practice, we can often use variables and object interchangeably. 
