# Python review 

Goals:
- recall basic Python vocabulary 
- practice markdown 

## Libraries and packages 
**library** a collection of code we can use to perform specfic tasks in our programs. 

**Numpy**: 
- core library for numerical computing in Python 
- many other libraries use NumPy arrays as building blocks 
- computations on NumPy are optimized for speed and memory usage

Let's import NumPy with **standard abbreviation** 


In [1]:
import numpy as np

## Variables 

**variable**: a name we assign to a particular object in Python 

Example: 

In [2]:
# Assign a small array to a variables a 
a = np.array([[1,2,2],[3,5,8]])


In [3]:
# Run cell with a variable name to show value
a

array([[1, 2, 2],
       [3, 5, 8]])

In [4]:
# Use 'print' function to print the value 
print(a)

[[1 2 2]
 [3 5 8]]


## Objects 

**object** (informally speaking) is a bundle of *properties* and *actions* about something specfic. 

Example: 
Object: data frame 
Properties: number of tows, names of the columns, date created 
Actions: Selecting a specific row, adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables. 

In practice, we can often use variables and object interchangeably. 

## Types

Every object in Python has a type and the type tells us what kind of object it is. 

We can also call the type of an object, the **class** of an object and they both mean what kind of object we have. 




In [7]:
print(a)

# Check the type/class of a variable/object by using 'type' function
type(a)

[[1 2 2]
 [3 5 8]]


numpy.ndarray

In [9]:
print(a[0,0])

# Check the type of an entry on the array by indexing 
type(a[0,0])

1


numpy.int64

Notice that `type(a[0,0])` is `numpy.int64'` and not just the standard Python integer type. This is telling us that 1 is the integer stored as 64-bit number.  

In [11]:
# Access number 5
a[1,1]

5

## Functions

`print` was out first example of a python **function**.

Functions take in a set of **arguments** and those arguments create an **ouput**. 

argument = parameter 
we can ssk for info about a function through ?function. 

This information is a **docstring**. 

In [12]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

This information is a **docstring**.

A function has two types of arguments: 
- **non-optional argument**: arguments *your* need to speficiy for the function to do somehting 

-**optional arguments**: Arguments that are prefilled with a default value by the funciton. You can override them. Optional arguments appear inside he parenthesis in the form `optional_argument=default_value`. 

In [13]:
print('changing the default end argument', end=':)')

changing the default end argument:)

## Attributes and methods 

An object in python has attributes and methods. 

-**attributes**: A property of an object, soem pieces of information about it 

-**method**: a procedure assoiciated with an object 

## Check in 

Fish attributes: 
- length, color, species
- die(), bite(), swim()

**Example**
Attributes for `numpy.arrays`

We can access a variable's attributes and methods by adding a period `.` at the end of the variable's name. 

`variable.method()` or `variable.attribute`

In [15]:
a.shape

(2, 3)

In [16]:
type(a.shape)

tuple

In [18]:
# Methods examples 
# min() returns the minimum value along a specified axis
a.min(axis=0)

array([1, 2, 2])

# Check in

We can also call the min method without any parameters 

In [21]:
a.min()
# Optional parameter?

1

In [20]:
a

array([[1, 2, 2],
       [3, 5, 8]])

Remember: methods are functions associated with object.

In [23]:
type(a.min)

builtin_function_or_method

## Exercise 

1. Read the `print` function help. What is the type of the argument `sep`? Is this an optional or non-optional argument? Why? 

2. Create two new variables, one with the integer value 77 and another one with the string 99. 

3. Use your variables to print `77%99%77` by chaning the value of one of the optional arguments in `print`.

In [26]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

sep: string between values is a space, it is optional

In [27]:
a = 77 
b = 99

In [35]:
print(a,b,a, sep='%') 
# Optional argument

77%99%77
